version: '3.3'

services:
  limesurvey:
    image: acspri/quexf
    volumes:
     - ${WEBAPP_STORAGE_HOME}/site/images:/images
     - ${WEBAPP_STORAGE_HOME}/site/forms:/forms
     - ${WEBAPP_STORAGE_HOME}/site/quexf:/opt/quexf
    environment:
      QUEXF_DB_PASSWORD: example
      QUEXF_ADMIN_PASSWORD: password
      QUEXF_HTPASSWD_PATH: /opt/quexf/password
      QUEXF_HTGROUP_PATH: /opt/quexf/group
      QUEXF_MULTIPLE_CHOICE_MIN_FILLED: 0.85
      QUEXF_MULTIPLE_CHOICE_MAX_FILLED: 0.60
      QUEXF_SINGLE_CHOICE_MIN_FILLED: 0.85
      QUEXF_SINGLE_CHOICE_MAX_FILLED: 0.60
      QUEXF_HORI_WIDTH_BOX: 58
      QUEXF_VERT_WIDTH_BOX: 58
      QUEXF_BARCODE_TLX_PORTION: 0.5
      MYSQL_SSL_CA: BaltimoreCyberTrustroot.crt.pem
      WEBSITES_ENABLE_APP_SERVICE_STORAGE: TRUE
    restart: always
