version: '2'

services:

  quexf:
    image: acspri/quexf
    ports:
      - 8081:80
    environment:
      QUEXF_DB_PASSWORD: example
      QUEXF_ADMIN_PASSWORD: password
      QUEXF_HTPASSWD_PATH: /opt/quexf/password
      QUEXF_HTGROUP_PATH: /opt/quexf/group

  mysql:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: example
