version: '2'

services:

  quexf:
    image: acspri/quexf:1.20.9
    build: .
    ports:
      - 8079:80
    environment:
      QUEXF_DB_PASSWORD: example
      QUEXF_ADMIN_PASSWORD: password
      QUEXF_HTPASSWD_PATH: /opt/quexf/password
      QUEXF_HTGROUP_PATH: /opt/quexf/group
      QUEXF_MULTIPLE_CHOICE_MIN_FILLED: 0.85
      QUEXF_MULTIPLE_CHOICE_MAX_FILLED: 0.60
      QUEXF_SINGLE_CHOICE_MIN_FILLED: 0.85
      QUEXF_SINGLE_CHOICE_MAX_FILLED: 0.60
      QUEXF_HORI_WIDTH_BOX: 58
      QUEXF_VERT_WIDTH_BOX: 58
      QUEXF_BARCODE_TLX_PORTION: 0.5
    restart: unless-stopped

  mysql:
    image: mariadb:10.5
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: example
